owner: FlipTheBoard
repo: FTB-upptime

sites:
  - name: Stage
    url: https://stage.fliptheboard.ru
  - name: Mobile
    url: https://mobile.fliptheboard.ru
  - name: ERP
    url: https://erp.fliptheboard.ru
  - name: Wiki
    url: https://wiki.fliptheboard.ru
  - name: GitLab
    url: https://git.fliptheboard.ru

status-website:
  baseUrl: /FTB-upptime
  name: FlipTheBoard Status
  introTitle: "Статус сервисов FlipTheBoard"
  introMessage: Мониторинг доступности сервисов [FlipTheBoard](https://fliptheboard.ru) в реальном времени на основе GitHub Actions.
  navbar:
    - title: Статус
      href: /
    - title: GitHub
      href: https://github.com/FlipTheBoard/FTB-upptime
